#!/usr/bin/env python
import os
import sys

env = SConscript("godot-cpp/SConstruct")

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["src/"])
env.Append(CPPPATH=["../cpp_version/"])  # Add path to your DLL headers

# Add library path and link the DLL
if env["platform"] == "windows":
    env.Append(LIBPATH=["../cpp_version/x64/Debug/"])  # Path to your DLL lib file
    env.Append(LIBS=["pmugg dll"])  # Name of your lib file (without .lib extension)
    # Suppress warning about illegal characters in third-party JSON header
    env.Append(CXXFLAGS=["/wd4828"])

sources = Glob("src/*.cpp")

# On Linux, include PMUGG source files directly since we don't have a prebuilt library
if env["platform"] == "linux":
    # Enable exceptions for PMUGG code
    env.Append(CXXFLAGS=["-fexceptions"])
    
    # Add PMUGG source files
    pmugg_sources = [
        "../cpp_version/pmugg dll/generate.cpp",
        "../cpp_version/mutator.cpp",
        "../cpp_version/memory_counter.cpp",
        "../cpp_version/settings.cpp",
        "../cpp_version/graph_grammar.cpp",
    ]
    
    # Add sources from subdirectories
    pmugg_sources += Glob("../cpp_version/geometry/*.cpp")
    pmugg_sources += Glob("../cpp_version/graph/*.cpp")
    pmugg_sources += Glob("../cpp_version/graph_drawing/*.cpp")
    pmugg_sources += Glob("../cpp_version/graph_morphism/*.cpp")
    pmugg_sources += Glob("../cpp_version/grammar_rules/*.cpp")
    pmugg_sources += Glob("../cpp_version/placements/*.cpp")
    pmugg_sources += Glob("../cpp_version/primitives/*.cpp")
    pmugg_sources += Glob("../cpp_version/util/*.cpp")
    pmugg_sources += Glob("../cpp_version/json versioning/*.cpp")
    
    sources += pmugg_sources

if env["platform"] == "macos":
    # Enable exceptions for PMUGG code
    env.Append(CXXFLAGS=["-fexceptions"])

    # Add PMUGG source files
    pmugg_sources = [
        "../cpp_version/pmugg dll/generate.cpp",
        "../cpp_version/mutator.cpp",
        "../cpp_version/memory_counter.cpp",
        "../cpp_version/settings.cpp",
        "../cpp_version/graph_grammar.cpp",
    ]
    
    # Add sources from subdirectories
    pmugg_sources += Glob("../cpp_version/geometry/*.cpp")
    pmugg_sources += Glob("../cpp_version/graph/*.cpp")
    pmugg_sources += Glob("../cpp_version/graph_drawing/*.cpp")
    pmugg_sources += Glob("../cpp_version/graph_morphism/*.cpp")
    pmugg_sources += Glob("../cpp_version/grammar_rules/*.cpp")
    pmugg_sources += Glob("../cpp_version/placements/*.cpp")
    pmugg_sources += Glob("../cpp_version/primitives/*.cpp")
    pmugg_sources += Glob("../cpp_version/util/*.cpp")
    pmugg_sources += Glob("../cpp_version/json versioning/*.cpp")
    
    sources += pmugg_sources

    library = env.SharedLibrary(
        "demo/bin/libgdexample.{}.{}.framework/libgdexample.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
elif env["platform"] == "ios":
    if env["ios_simulator"]:
        library = env.StaticLibrary(
            "demo/bin/libgdexample.{}.{}.simulator.a".format(env["platform"], env["target"]),
            source=sources,
        )
    else:
        library = env.StaticLibrary(
            "demo/bin/libgdexample.{}.{}.a".format(env["platform"], env["target"]),
            source=sources,
        )
else:
    library = env.SharedLibrary(
        "demo/bin/libgdexample{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
