#include "pch.h"
#include "settings.h"



Json globalSettings = {
    {"Extents", vector<int>{30, 20, 10}},
    {"Incremental Mutation", true},
    {"Use Boundary Cells", false},
    {"Model Piece Example", "ms.ESCHER_EXAMPLE"},
    {"Redraw Time", 0.1f},
    {"Allow Rotations", false},
    {"Bend Edges", false},
    {"Careful Bending", true},
    {"Bend Time Start", 0},
    {"Allow Scaling", false},
    {"Import Scale", 1.0f},
    {"Many Rigid Bent Options", true},
    {"Many Flexible Bent Options", false},
    {"Remove Good Vertices", false},
    {"Bend Multiplier", 1},
    {"Snap Grid", true},
    {"Snap Grid Spacing", 20},
    {"Major Grid Spacing", 40},
    {"Snap Angle", 20},
    {"Mutator Effort Limit", 20},
    {"Prefer Ground", 0.9f},
    {"Empty Border", true},
    {"Beta", 1},
    {"Snapping Effort Limit", 100},
    {"Bad Vertex", 10},
    {"HalfEdge Conflict", 1},
    {"HalfEdge Conflict Base", 1.1f},
    {"Flexible Edge Length", 50},
    {"Rigid Edge Length", 500},
    {"Ideal Length", 0.5f},
    {"Face", 5},
    {"Completion", 4},
    {"Valence", 0},
    {"Component", 20},
    {"State Density", 2},
    {"Component Scale", 10},
    {"Component Base", 1.5f},
    {"Face Base", 1.1f},
    {"Visibility", 0},
    {"Closible HalfEdge Index", 1},
    {"Closible Angle", 200},
    {"Desired Edges", 200},
    {"Desired Edges Cost", 10000},
    {"Desired Vertex Weight", 100},
    {"Free Vertices", true},
    {"Kill Junctions", true},
    {"Full Move", true},
    {"Modify center", false},
    {"Immutable Ground", true},
    {"Edge Weld Probability", 0.7f},
    {"Node Debug", -1},
    {"Debug Alerts", false},
    {"Max Time Enabled", false},
    {"Max Time", 10},
    {"Max Iterations", 100},
    {"Generations", 5},
    {"Max Connectors", 100},
    {"Winding Enabled", true},
    {"Stubs Enabled", false},
    {"Match Backwards", true},
    {"Use Chain Map", false},
    {"Monotonic", true},
    {"Super Edges", true},
    {"Show Inactives", false},
    {"Multiple Attachees", false},
    {"Grounded", true},
    {"Winding Penalty", 1},
    {"Winding Penalty New", 10},
    {"New Seed", false},
    {"Seed", 1},
    {"Task Stop", -1},
    {"Task Step", 1},
    {"Debug Each Task", false},
    {"Fast Matrix Math", true},
    {"Report Timings", true},
    {"Show Grid", false},
    {"High Smoothing", true},
    {"Use WebGL", false},
    {"Show Faces", true},
    {"Cut Holes", true},
    {"Fewer Start Productions", false},
    {"Example View", true},
    {"Use Graph", true},
    {"Pause when finished", false}
};

